### ISSUE TITLE
can I freely use the received audio

### ISSUE THREAD

**Issue by Djastas** [riffusion/riffusion#124]
this neural network turns out to be a good way to write an OST for games and I would like to use it
(I'm sorry if I filled out the form incorrectly, I don't understand github well.)

**Comment by mepc36** [comment]
Hey @Djastas, yes you can use the audio freely. Code like Riffusion is released with a license. Riffusion's license can be found here:

https://github.com/riffusion/riffusion/blob/main/LICENSE

Riffusion's license is known as the MIT license. This is what the MIT license allows: 

--------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
associated documentation files (the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge, publish, distribute,
sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.
--------

As you can see, you're allowed to "deal in the Software without restriction", which I **think** covers the software's outputs too (i.e., the audio for your OST). Please note that I'm not a lawyer and this is not legal advice. You can learn more about the MIT license here:

https://en.wikipedia.org/wiki/MIT_License

Also, you did fine using GitHub haha. Good luck!

**Comment by itsnotlupus** [comment]
The MIT license applies to the code in the repository. 

Models typically have their own license. For example https://huggingface.co/riffusion/riffusion-model-v1 uses the [stable diffusion license](https://github.com/CompVis/stable-diffusion/blob/main/LICENSE), which they call the "CreativeML Open RAIL-M" license.

Most of it seems reasonable, but the "Use Restrictions" at the bottom are pretty far from what an Open Source license would have.
I don't know that any of them apply to your situation, but it's worth looking over.

**Comment by SethForsgren** [comment]
Closing since this question is not about the code in this repo. The HF model card notes that it intended for research purposes.
