### ISSUE TITLE
How to convert audio to a spectrogram picture?  

### ISSUE THREAD

**Issue by constantly-asks** [riffusion/riffusion#13]
Maybe I don't know how to Google, but I only found how to visualize, which is not like what is shown in your article.

**Comment by hmartiro** [comment]
I will add an example this weekend!

**Comment by chavinlo** [comment]
Not official but https://github.com/chavinlo/riffusion-manipulation

**Comment by nikuson** [comment]
> Не официально, но https://github.com/chavinlo/riffusion-manipulation

Thank you so much, I will use your implementation.  But I'm still wondering what kind of example the author of the repository will share.

**Comment by constantly-asks** [comment]
> Not official but https://github.com/chavinlo/riffusion-manipulation

not working via pycharm terminal

**Comment by hmartiro** [comment]
Please see: https://github.com/riffusion/riffusion/blob/main/riffusion/cli.py#L19

Using the class: https://github.com/riffusion/riffusion/blob/main/riffusion/spectrogram_image_converter.py
