### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wedgeewoo** [riffusion/riffusion#23]
![image](https://user-images.githubusercontent.com/112199050/208228481-4522c6e1-eb2b-4119-9775-d796e8fc2bb1.png)

**Comment by wedgeewoo** [comment]
I was able to bybass the IndexError by removing safety_checker=safety_checker, line 54 in riffusion_pipeline.py. Tried to connect to the localhost but I get a 404 page

**Comment by hmartiro** [comment]
What version of diffusers do you have installed?

**Comment by wedgeewoo** [comment]
0.4.1

**Comment by wedgeewoo** [comment]
I need 0.90.0 right?

**Comment by wedgeewoo** [comment]
i made a .env.local file containing RIFFUSION_FLASK_URL=http://127.0.0.1:3013/run_inference/
name the file ".env.local"

Now it runs, just have to figure out how to make models with my music now
