### ISSUE TITLE
Data preparing process

### ISSUE THREAD

**Issue by vivian556123** [riffusion/riffusion#30]
Hi, Thanks for your wonderful work!
I tried to use audio.py to create the Mel spectrogram of size 512*512, but the Mel spectrograms are badly created. Could you please share more parameters information like n_fft, hop_size, win_size and etc?

I tried to use n_fft = 1024, hop_length = 256, win_length=1024 to extract melspec with n_mels = 512, but the picture is like that````
![rqfQRErjfk8](https://user-images.githubusercontent.com/45330476/208882110-46207f4f-e9e4-44a2-96d5-f2bd384fe632.jpg)

**Comment by hmartiro** [comment]
Hey @vivian556123 - to customize the spectrogram parameters beyond the defaults I suggest reading https://github.com/riffusion/riffusion/blob/main/riffusion/spectrogram_converter.py and particularly the torchaudio documentation of the relevant classes at https://pytorch.org/audio/stable/transforms.html. It will take some understanding to customize. Adding a note to SpectrogramParams to this end.
