### ISSUE TITLE
Add audio2audio demo

### ISSUE THREAD

**Issue by hmartiro** [riffusion/riffusion#58]

**Comment by fhackenberger** [comment]
Hey @hmartiro would you mind sharing where to find the code for the audio2audio demo? Thank you!

**Comment by hmartiro** [comment]
https://github.com/riffusion/riffusion/blob/main/riffusion/streamlit/pages/audio_to_audio.py

**Comment by fhackenberger** [comment]
Ah so that one inits the engine with an image and transitions from prompt to prompt. Is there also a way to transition from image to image? Think: crossfade two existing tracks.
