### ISSUE TITLE
can't use riffusion on my new system.

### ISSUE THREAD

**Issue by MostroW1502** [riffusion/riffusion#61]
Using a 4090RTX is throwing me this error "nvrtc: error: invalid value for --gpu-architecture (-arch)" at the end of a listing what looks like source code displayed.

Can submit other system details if need be, but the nvrtc message at the end leads me to believe that my videocard is not supported (yet)?

**Comment by hmartiro** [comment]
This seems like it might be a torch version issue. What does this say:

```
import torch
torch.cuda.is_available()```

**Comment by MostroW1502** [comment]
at first i couldn't even import torch.

so i installed torch for python310, after i ran the import and function it gave me a "False" even though the pip3 install went fine and says "Requirement already satisfied" when i tried to install again.

i tried this as well: torch.zeros(1).cuda()
i threw me the error: Torch is not compiled with CUDA enabled

i've got version 12 installed of CUDA, Python version is 3.10.8

**Comment by hmartiro** [comment]
I'm closing this as it's not specific to riffusion
