### ISSUE TITLE
[Playground] Audio player shows error on Safari

### ISSUE THREAD

**Issue by Navenamseeg** [riffusion/riffusion#85]
Receiving error for final stitches version of audio in audio2audio. On iPhone. Prompted with a stereo mp3. 
![3790AF4D-9E63-42B0-AD01-654C8E93DB2E](https://user-images.githubusercontent.com/122689816/212484423-4523a1ed-ace4-485f-bcfc-ec77729b7e59.png)
![D7E76CA9-F994-4E6E-9FD8-14A3982E64A3](https://user-images.githubusercontent.com/122689816/212484435-4007cbe3-c81f-4b09-8efa-edbaa27f36ec.png)

**Comment by hmartiro** [comment]
You're on Safari right @Navenamseeg ? Can you try on Chrome?

**Comment by hmartiro** [comment]
Closing as duplicate of #77
